name: redgrid

services:
  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    restart: unless-stopped
