import { TASK_STATUS } from "@/types/domain-types";

export const STATE_MACHINE_NODES: {
    id: string;
    x: number;
    y: number;
    w: number;
    h: number;
    color: string;
    text: string;
    border?: string;
}[] = [
    {
        id: "VALIDATION",
        x: 200,
        y: 20,
        w: 120,
        h: 32,
        color: "var(--color-zinc-800)",
        text: "var(--color-zinc-400)",
    },
    {
        id: "ORACLE TEST",
        x: 200,
        y: 100,
        w: 120,
        h: 32,
        color: "var(--border)",
        text: "var(--primary)",
        border: "var(--primary)",
    },
    {
        id: TASK_STATUS.SUCCESS,
        x: 60,
        y: 190,
        w: 100,
        h: 28,
        color: "var(--border)",
        text: "var(--success)",
        border: "var(--border)",
    },
    {
        id: "VALIDATED",
        x: 40,
        y: 260,
        w: 120,
        h: 32,
        color: "var(--border)",
        text: "var(--success)",
        border: "var(--border)",
    },
    {
        id: TASK_STATUS.FAILED,
        x: 340,
        y: 190,
        w: 100,
        h: 28,
        color: "var(--border)",
        text: "var(--destructive)",
        border: "var(--border)",
    },
    {
        id: "DIAGNOSIS",
        x: 330,
        y: 260,
        w: 120,
        h: 32,
        color: "var(--border)",
        text: "var(--primary)",
        border: "var(--border)",
    },
    {
        id: "CORRECTABLE",
        x: 230,
        y: 340,
        w: 120,
        h: 28,
        color: "var(--border)",
        text: "var(--warning)",
        border: "var(--border)",
    },
    {
        id: "FUNDAMENTAL",
        x: 420,
        y: 340,
        w: 120,
        h: 28,
        color: "var(--border)",
        text: "var(--destructive)",
        border: "var(--border)",
    },
    {
        id: "ADAPT",
        x: 230,
        y: 410,
        w: 100,
        h: 28,
        color: "var(--color-zinc-900)",
        text: "var(--color-zinc-500)",
        border: "var(--border)",
    },
    {
        id: "RULED_OUT",
        x: 420,
        y: 410,
        w: 100,
        h: 28,
        color: "var(--color-zinc-900)",
        text: "var(--color-zinc-600)",
        border: "var(--border)",
    },
    {
        id: "RETRY",
        x: 230,
        y: 480,
        w: 100,
        h: 28,
        color: "var(--border)",
        text: "var(--primary)",
        border: "var(--border)",
    },
];

export const STATE_MACHINE_EDGES = [
    {
        x1: 260,
        y1: 52,
        x2: 260,
        y2: 100,
        label: "",
    },
    {
        x1: 260,
        y1: 132,
        x2: 110,
        y2: 190,
        label: TASK_STATUS.SUCCESS,
    },
    {
        x1: 260,
        y1: 132,
        x2: 390,
        y2: 190,
        label: TASK_STATUS.FAILED,
    },
    {
        x1: 110,
        y1: 218,
        x2: 100,
        y2: 260,
        label: "",
    },
    {
        x1: 390,
        y1: 218,
        x2: 390,
        y2: 260,
        label: "",
    },
    {
        x1: 390,
        y1: 292,
        x2: 290,
        y2: 340,
        label: "CORRECTABLE",
    },
    {
        x1: 390,
        y1: 292,
        x2: 480,
        y2: 340,
        label: "FUNDAMENTAL",
    },
    {
        x1: 290,
        y1: 368,
        x2: 280,
        y2: 410,
        label: "",
    },
    {
        x1: 480,
        y1: 368,
        x2: 470,
        y2: 410,
        label: "",
    },
    {
        x1: 280,
        y1: 438,
        x2: 280,
        y2: 480,
        label: "",
    },
];
